version: '3.8'
services:

  demo: 
    build: 
      context: "../../Demo/"
      dockerfile: "Dockerfile"
    hostname: demo
    container_name: demo
    ports:
      - "5010:80"
    restart: always
    environment:
      "PUBLIC_PORT": "80"

  ocelot-gateway:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "5011:80"
    links:
      - demo
    depends_on:
      - demo