version: '3.8'
services:

  demo: 
    build: 
      context: "../../SolutionService/"
      dockerfile: "Dockerfile"
    hostname: solution-service
    container_name: solution-service
    ports:
      - "5000:80"
    restart: always
    environment:
      "PUBLIC_PORT": "80"

  ocelot-gateway:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "5011:80"
    links:
      - solution-service
    depends_on:
      - solution-service